scoring:
  scoring_version: v1.0
  model_path: '${core.artifacts_path}/efficientnet/{scoring_version}/model/10_back'

training:
  pre_trained_weights: '${core.artifacts_path}/efficientnet/{scoring_version}/model/10_back'
  batch_size: 2
  epoch: 1
  verbose: 2
  test_size: 0.15
  learning_rate: 0.0001

