scoring:
  scoring_version: v3.0
  model_path: '${core.artifacts_path}/yolo/{scoring_version}/model/weights/best.pt'
  #"C:\Users\anandu.nandakuma\Desktop\Cat_id\cat_visual_id-master\artifacts\yolo\v2.0\model\weights\best-int8.tflite"
  device: 'cpu'
  conf_threshold: 0.4
  iou_threshold: 0.4

training:
  pre_trained_weights: '${core.artifacts_path}/yolo/{scoring_version}/model/weights/best.pt'
  epochs: 4
  batch_size: 3
  rect: False
  device: 'cpu'
  save_period: 1
  patience: 100
  freeze: 0
  resume: False
  nosave: False
  noval: False
  noautoanchor: False
  cache: 'ram'
  image_weights: False
  multi_scale: False
  single_cls: False
  adam: False
  sync_bn: False
  workers: 8
  quad: False
  linear_lr: False
  label_smoothing: 0.0
  local_rank: -1
  entity: None
  upload_dataset: False
  bbox_interval: -1
  artifact_alias: latest

